[project]
name = "doc-automation"
version = "0.1.0"
description = "Add your description here"
readme = "Readme.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "ipykernel>=7.3.0",
    "ollama>=0.6.2",
    "python-multipart>=0.0.20",
    "uvicorn>=0.35.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
]
